In [64]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
import tensorflow as tf

Housing Dataset
---------------


**Dataset characteristics:**

    :Number of instances: 54,670

    :Number of Attributes: 8

    :Attribute Information:

        -'Estimated_Median_Household_Income' Median household income for the year for the city
        -'2021_estimated_population' estimated population for the city in 2021
        -'2020_census' population by census in 2020
        -'Median_Taxes' Median taxes paid for the household in the city
        -'Median_Rent' Median rent paid in the city for each year
        -'AnnualAverageRate30Year' Average mortgage rate for city for 30 year mortgages
        -'Median_Monthly_Income' Median income divided by 12
        -'Monthly_Affordability_Limit' based on 30% of median monthly income

    :Missing Attribute Values:

This dataset was obtained from zillow research data and US census data from 2011 to 2021.

The target variable is 'affordability_home_30yr_Payment_20_Perc_Down'

In [74]:
df = pd.read_csv(r"C:\Users\mattw\Documents\Bootcamp\Group Project\Resources\Master_Data_Set.csv")
df

,Identifier,City_Rank_by_Population(2021),State,State_Abbreviation,City,Observation_Date,Single_Family_Median_Typical_Home_Value,One_Bedroom_Median_Typical_Home_Value,Two_Bedroom_Median_Typical_Home_Value,Three_Bedroom_Median_Typical_Home_Value,...,affordability_3br_30yr_Payment_10_Perc_Down,affordability_3br_30yr_Payment_20_Perc_Down,affordability_4br_15yr_Payment_10_Perc_Down,affordability_4br_15yr_Payment_20_Perc_Down,affordability_4br_30yr_Payment_10_Perc_Down,affordability_4br_30yr_Payment_20_Perc_Down,affordability_5_plus_br_15yr_Payment_10_Perc_Down,affordability_5_plus_br_15yr_Payment_20_Perc_Down,affordability_5_plus_br_30yr_Payment_10_Perc_Down,affordability_5_plus_br_30yr_Payment_20_Perc_Down
0,201101,1,New York,NY,New York,1/1/2011,460824.0,419555.5,549450.5,455413.0,...,0.60,0.67,0.36,0.40,0.51,0.58,0.29,0.32,0.41,0.46
1,201201,1,New York,NY,New York,1/1/2012,453166.5,421581.5,549293.0,448447.0,...,0.69,0.77,0.39,0.44,0.59,0.66,0.31,0.35,0.47,0.53
2,201301,1,New York,NY,New York,1/1/2013,467125.5,445182.5,579800.5,461446.5,...,0.66,0.74,0.38,0.43,0.56,0.63,0.30,0.34,0.44,0.50
3,201401,1,New York,NY,New York,1/1/2014,499898.0,487199.5,634870.5,493995.0,...,0.61,0.69,0.36,0.40,0.51,0.58,0.28,0.31,0.40,0.45
4,201501,1,New York,NY,New York,1/1/2015,526189.0,536285.0,689511.5,522588.5,...,0.63,0.71,0.36,0.40,0.53,0.59,0.27,0.30,0.40,0.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
776,201775,75,New Jersey,NJ,Jersey City,1/1/2017,408525.0,471067.5,537922.5,458794.5,...,0.84,0.95,0.59,0.66,0.87,0.98,0.55,0.61,0.81,0.91
777,201875,75,New Jersey,NJ,Jersey City,1/1/2018,459463.0,503269.5,568473.0,501645.0,...,0.79,0.89,0.55,0.62,0.80,0.90,0.50,0.57,0.73,0.82
778,201975,75,New Jersey,NJ,Jersey City,1/1/2019,489001.0,490562.5,566059.0,523939.5,...,0.91,1.03,0.60,0.68,0.90,1.02,0.56,0.62,0.83,0.94
779,202075,75,New Jersey,NJ,Jersey City,1/1/2020,514131.5,487710.5,570039.5,541306.0,...,0.92,1.03,0.58,0.65,0.90,1.02,0.52,0.59,0.82,0.92
780,202175,75,New Jersey,NJ,Jersey City,1/1/2021,569324.0,502310.0,594366.5,585132.5,...,0.93,1.04,0.58,0.65,0.90,1.01,0.53,0.59,0.83,0.93

In [76]:
df['affordability_home_30yr_Payment_20_Perc_Down'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 781 entries, 0 to 780
Series name: affordability_home_30yr_Payment_20_Perc_Down
Non-Null Count  Dtype
--------------  -----
781 non-null    bool
dtypes: bool(1)
memory usage: 909.0 bytes

In [78]:
x_columns = ['Estimated_Median_Household_Income', '2021_estimated_population', '2020_census', 'Median_Taxes', 'Median_Rent', 'AnnualAverageRate30Year','Median_Monthly_Income','Monthly_Affordability_Limit'] 
# 'home_30yr_Payment_20_Perc_Down', '1br_30yr_Payment_20_Perc_Down', '2br_30yr_Payment_20_Perc_Down', 
# '3br_30yr_Payment_20_Perc_Down', '4br_30yr_Payment_20_Perc_Down', '5_plus_br_30yr_Payment_20_Perc_Down', 'Median_Monthly_Income', 'Monthly_Affordability_Limit'



X = df[x_columns]
y=df['affordability_home_30yr_Payment_20_Perc_Down']

In [79]:
corr_df = X.corr()
corr_df

,Estimated_Median_Household_Income,2021_estimated_population,2020_census,Median_Taxes,Median_Rent,AnnualAverageRate30Year,Median_Monthly_Income,Monthly_Affordability_Limit
Estimated_Median_Household_Income,1.000000,1.607488e-02,1.861983e-02,0.664606,0.871692,-2.140559e-01,1.000000,1.000000
2021_estimated_population,0.016075,1.000000e+00,9.998610e-01,0.158370,0.124975,-6.951612e-16,0.016075,0.016075
2020_census,0.018620,9.998610e-01,1.000000e+00,0.161385,0.127955,-6.742022e-16,0.018620,0.018620
Median_Taxes,0.664606,1.583703e-01,1.613845e-01,1.000000,0.715111,-1.270912e-01,0.664606,0.664606
Median_Rent,0.871692,1.249748e-01,1.279552e-01,0.715111,1.000000,-2.154704e-01,0.871692,0.871692
AnnualAverageRate30Year,-0.214056,-6.951612e-16,-6.742022e-16,-0.127091,-0.215470,1.000000e+00,-0.214056,-0.214056
Median_Monthly_Income,1.000000,1.607497e-02,1.861993e-02,0.664606,0.871692,-2.140559e-01,1.000000,1.000000
Monthly_Affordability_Limit,1.000000,1.607540e-02,1.862035e-02,0.664606,0.871692,-2.140559e-01,1.000000,1.000000

In [80]:


X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [81]:


# model = LinearRegression()

nn_model = tf.keras.models.Sequential()
nn_model.add(tf.keras.layers.Dense(units=16, activation="relu", input_dim=8))
nn_model.add(tf.keras.layers.Dense(units=16, activation="relu"))
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the Sequential model together and customize metrics
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])


# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=50)

# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/50
19/19 [==============================] - 0s 942us/step - loss: 0.7483 - accuracy: 0.2957
Epoch 2/50
19/19 [==============================] - 0s 887us/step - loss: 0.6616 - accuracy: 0.6718
Epoch 3/50
19/19 [==============================] - 0s 887us/step - loss: 0.5938 - accuracy: 0.8325
Epoch 4/50
19/19 [==============================] - 0s 776us/step - loss: 0.5363 - accuracy: 0.8530
Epoch 5/50
19/19 [==============================] - 0s 997us/step - loss: 0.4894 - accuracy: 0.8547
Epoch 6/50
19/19 [==============================] - 0s 1ms/step - loss: 0.4511 - accuracy: 0.8530
Epoch 7/50
19/19 [==============================] - 0s 831us/step - loss: 0.4208 - accuracy: 0.8564
Epoch 8/50
19/19 [==============================] - 0s 942us/step - loss: 0.3968 - accuracy: 0.8581
Epoch 9/50
19/19 [==============================] - 0s 1ms/step - loss: 0.3781 - accuracy: 0.8598
Epoch 10/50
19/19 [==============================] - 0s 1ms/step - loss: 0.3629 - accuracy: 0.8632
Epoch 11/50
19/19 [==============================] - 0s 1ms/step - loss: 0.3497 - accuracy: 0.8667
Epoch 12/50
19/19 [==============================] - 0s 1ms/step - loss: 0.3360 - accuracy: 0.8701
Epoch 13/50
19/19 [==============================] - 0s 1ms/step - loss: 0.3240 - accuracy: 0.8718
Epoch 14/50
19/19 [==============================] - 0s 997us/step - loss: 0.3117 - accuracy: 0.8803
Epoch 15/50
19/19 [==============================] - 0s 1ms/step - loss: 0.3000 - accuracy: 0.8855
Epoch 16/50
19/19 [==============================] - 0s 1ms/step - loss: 0.2882 - accuracy: 0.8855
Epoch 17/50
19/19 [==============================] - 0s 1ms/step - loss: 0.2785 - accuracy: 0.8906
Epoch 18/50
19/19 [==============================] - 0s 942us/step - loss: 0.2683 - accuracy: 0.8940
Epoch 19/50
19/19 [==============================] - 0s 997us/step - loss: 0.2586 - accuracy: 0.8991
Epoch 20/50
19/19 [==============================] - 0s 831us/step - loss: 0.2497 - accuracy: 0.8991
Epoch 21/50
19/19 [==============================] - 0s 997us/step - loss: 0.2421 - accuracy: 0.9009
Epoch 22/50
19/19 [==============================] - 0s 1ms/step - loss: 0.2332 - accuracy: 0.9094
Epoch 23/50
19/19 [==============================] - 0s 831us/step - loss: 0.2263 - accuracy: 0.9128
Epoch 24/50
19/19 [==============================] - 0s 1ms/step - loss: 0.2187 - accuracy: 0.9197
Epoch 25/50
19/19 [==============================] - 0s 997us/step - loss: 0.2113 - accuracy: 0.9214
Epoch 26/50
19/19 [==============================] - 0s 887us/step - loss: 0.2042 - accuracy: 0.9231
Epoch 27/50
19/19 [==============================] - 0s 1ms/step - loss: 0.1964 - accuracy: 0.9282
Epoch 28/50
19/19 [==============================] - 0s 942us/step - loss: 0.1906 - accuracy: 0.9282
Epoch 29/50
19/19 [==============================] - 0s 831us/step - loss: 0.1854 - accuracy: 0.9316
Epoch 30/50
19/19 [==============================] - 0s 997us/step - loss: 0.1810 - accuracy: 0.9350
Epoch 31/50
19/19 [==============================] - 0s 997us/step - loss: 0.1765 - accuracy: 0.9368
Epoch 32/50
19/19 [==============================] - 0s 887us/step - loss: 0.1733 - accuracy: 0.9402
Epoch 33/50
19/19 [==============================] - 0s 1ms/step - loss: 0.1697 - accuracy: 0.9385
Epoch 34/50
19/19 [==============================] - 0s 887us/step - loss: 0.1663 - accuracy: 0.9385
Epoch 35/50
19/19 [==============================] - 0s 997us/step - loss: 0.1637 - accuracy: 0.9453
Epoch 36/50
19/19 [==============================] - 0s 1ms/step - loss: 0.1609 - accuracy: 0.9453
Epoch 37/50
19/19 [==============================] - 0s 831us/step - loss: 0.1598 - accuracy: 0.9402
Epoch 38/50
19/19 [==============================] - 0s 886us/step - loss: 0.1572 - accuracy: 0.9470
Epoch 39/50
19/19 [==============================] - 0s 887us/step - loss: 0.1552 - accuracy: 0.9453
Epoch 40/50
19/19 [==============================] - 0s 997us/step - loss: 0.1535 - accuracy: 0.9470
Epoch 41/50
19/19 [==============================] - 0s 997us/step - loss: 0.1519 - accuracy: 0.9436
Epoch 42/50
19/19 [==============================] - 0s 887us/step - loss: 0.1515 - accuracy: 0.9470
Epoch 43/50
19/19 [==============================] - 0s 915us/step - loss: 0.1493 - accuracy: 0.9504
Epoch 44/50
19/19 [==============================] - 0s 942us/step - loss: 0.1470 - accuracy: 0.9504
Epoch 45/50
19/19 [==============================] - 0s 942us/step - loss: 0.1453 - accuracy: 0.9504
Epoch 46/50
19/19 [==============================] - 0s 997us/step - loss: 0.1440 - accuracy: 0.9487
Epoch 47/50
19/19 [==============================] - 0s 942us/step - loss: 0.1427 - accuracy: 0.9538
Epoch 48/50
19/19 [==============================] - 0s 831us/step - loss: 0.1421 - accuracy: 0.9538
Epoch 49/50
19/19 [==============================] - 0s 887us/step - loss: 0.1398 - accuracy: 0.9538
Epoch 50/50
19/19 [==============================] - 0s 942us/step - loss: 0.1390 - accuracy: 0.9504
7/7 - 0s - loss: 0.1386 - accuracy: 0.9439 - 90ms/epoch - 13ms/step
Loss: 0.13862700760364532, Accuracy: 0.9438775777816772

In [84]:
nn_model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_4 (Dense)             (None, 16)                144

 dense_5 (Dense)             (None, 16)                272

 dense_6 (Dense)             (None, 1)                 17

=================================================================
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________

In [85]:
nn_model.save("Linear_Regression.h5")